### ISSUE TITLE
Add Edit page and connect it to api

### ISSUE THREAD

**Issue by Shadow-rR** [Shadow-rR/TaskApp#1]
@

**Comment by Sagargajare** [comment]
Hi, @Shadow-rR I worked on flask and reactjs. I want to contribute to your project. Can You explain in detail and assign this issue to me.

**Comment by Shadow-rR** [comment]
So basically if you open the app it will have an option to view the added task and edit it, but please don't bother with this issue as it has already been assigned . You are most welcome to try the other issues
